name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *" # Executa diariamente
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar o repositório
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Instalar dependencies
        run: |
          pip install --upgrade pip
          pip install git+https://github.com/Platane/snk.git
      
      - name: Gerar snake animation
        run: |
          snk generate --output github-contribution-grid-snake.svg

      - name: Adicionar animação ao branch de saída
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
          publish_branch: output
